Instrument.create!(order: '100', name: 'Flute')
Instrument.create!(order: '110', name: 'Oboe')
Instrument.create!(order: '120', name: 'Clarinet')
Instrument.create!(order: '130', name: 'Bassoon')
Instrument.create!(order: '200', name: 'Horn I')
Instrument.create!(order: '210', name: 'Horn II')
Instrument.create!(order: '220', name: 'Horn')
Instrument.create!(order: '230', name: 'Trumpet')
Instrument.create!(order: '240', name: 'Trombone')
Instrument.create!(order: '250', name: 'Tuba')
Instrument.create!(order: '300', name: 'Timpani')
Instrument.create!(order: '310', name: 'Percussion')
Instrument.create!(order: '315', name: 'Marimba')
Instrument.create!(order: '311', name: 'Harpsichord')
Instrument.create!(order: '320', name: 'Piano')
Instrument.create!(order: '320', name: 'Organ')
Instrument.create!(order: '400', name: 'Guitar')
Instrument.create!(order: '500', name: 'Violin I')
Instrument.create!(order: '510', name: 'Violin II')
Instrument.create!(order: '520', name: 'Violin')
Instrument.create!(order: '530', name: 'Viola I')
Instrument.create!(order: '540', name: 'Viola II')
Instrument.create!(order: '550', name: 'Viola')
Instrument.create!(order: '560', name: 'Cello I')
Instrument.create!(order: '570', name: 'Cello II')
Instrument.create!(order: '580', name: 'Cello')
Instrument.create!(order: '590', name: 'Double bass')
Instrument.create!(order: '800', name: 'Soprano')
Instrument.create!(order: '802', name: 'Mezzo-soprano')
Instrument.create!(order: '810', name: 'Alto')
Instrument.create!(order: '820', name: 'Tenor')
Instrument.create!(order: '825', name: 'Baritone')
Instrument.create!(order: '830', name: 'Bass')
Instrument.create!(order: '900', name: 'Composer-in-Residence')
Instrument.create!(order: '910', name: 'Distinguished Composer-in-Residence')
Instrument.create!(order: '920', name: 'Young Composer')
Instrument.create!(order: '930', name: 'Bow Maker')
Instrument.create!(order: '940', name: 'Guest Speaker')
Instrument.create!(order: '1000', name: 'recording Producer and engineer')
Instrument.create!(order: '2000', name: 'Production')
